# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6306dc7152d9dd079e210a602f3dc987865893a078e35ced83508138353eca1c3a1e4e9f5c58af2b8bd3fac5603cc9c81860622a61c9568ce68c4cf7d57c4d80

test:
  secret_key_base: afd8cacc42aeec248f7bfa35073562f81f27b683470e2426bfcd0b8dbb07bb373deb9655109c33367358f4f73e17669aed61b29afd9b950187d046c2657c3d66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
